// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lib_Database.Database.Migrations.ApplicationDbContextMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210822115723_ApplicationDbContext_Initial")]
    partial class ApplicationDbContext_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Database.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Domain.AppModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MailServerUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailServerUserPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToEmailAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MailServerUserName = "===============",
                            MailServerUserPassword = "===============",
                            SmtpServer = "===============",
                            ToEmailAddress = "==============="
                        });
                });

            modelBuilder.Entity("Domain.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactEntityCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactEntityCategoryId");

                    b.ToTable("ContactEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "5 Grand Lodge, London UK",
                            ContactEntityCategoryId = 3,
                            ContactName = "Jane Doe",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(575), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "jane@doe.com",
                            FirstName = "Jane",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Doe",
                            Phone = "01111111111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "14 The Glades, New York US",
                            ContactEntityCategoryId = 4,
                            ContactName = "Tom Browne",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3214), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tom@browne.com",
                            FirstName = "Tom",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Browne",
                            Phone = "02111111111"
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 Hoble House, Penge, London UK",
                            ContactEntityCategoryId = 6,
                            ContactName = "Lucy Smith",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3222), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "lucy@smith.com",
                            FirstName = "Lucy",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Smith",
                            Phone = "03111111111"
                        },
                        new
                        {
                            Id = 4,
                            Address = "11 Broad Lane, Paris France",
                            ContactEntityCategoryId = 5,
                            ContactName = "Halie Jones",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3224), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "halie@jones.com",
                            FirstName = "Halie",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Jones",
                            Phone = "04111111111"
                        },
                        new
                        {
                            Id = 5,
                            Address = "A List Ltd Address, NY USA",
                            ContactEntityCategoryId = 7,
                            ContactName = "A List Ltd.",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3225), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Steve@AListLtd.com",
                            FirstName = "Steve",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Marriott",
                            Phone = "05111144111"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Antonio's Address, Siville Spain",
                            ContactEntityCategoryId = 7,
                            ContactName = "MicroTech",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3230), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Antonio@MicroTech.com",
                            FirstName = "Antonio",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Bolt",
                            Phone = "06111111111"
                        },
                        new
                        {
                            Id = 7,
                            Address = "McKenzie Address, Clidesdale Scotland",
                            ContactEntityCategoryId = 1,
                            ContactName = "McKenzie Porter",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3231), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "McKenzie@Email.com",
                            FirstName = "McKenzie",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Porter",
                            Phone = "07111112211"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Barry's Address, St. Kitts",
                            ContactEntityCategoryId = 1,
                            ContactName = "Barry Holland",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3233), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Barry@Email.com",
                            FirstName = "Barry",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Holland",
                            Phone = "08111111111"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Millie's Address, Gre Ireland",
                            ContactEntityCategoryId = 1,
                            ContactName = "Millie Higgins",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3234), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Millie@Email.com",
                            FirstName = "Millie",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Jones",
                            Phone = "09111111111"
                        },
                        new
                        {
                            Id = 10,
                            Address = "The Artz Address, Canada",
                            ContactEntityCategoryId = 7,
                            ContactName = "The Artz",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3236), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Emma@TheArtz.com",
                            FirstName = "Emma",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Pradas",
                            Phone = "01011191111"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Clive's Address, Ilford UK",
                            ContactEntityCategoryId = 4,
                            ContactName = "Clive Hilton",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3238), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Clive@Email.com",
                            FirstName = "Clive",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Hilton",
                            Phone = "04111111112"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Sharon's Address, Barbados",
                            ContactEntityCategoryId = 1,
                            ContactName = "Sharon Clark",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3239), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Sharon@Email.com",
                            FirstName = "Sharon",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Jones",
                            Phone = "04171111113"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Tony's Address, London",
                            ContactEntityCategoryId = 6,
                            ContactName = "Tony Blaze",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3241), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Tony@Email.com",
                            FirstName = "Tony",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Blaze",
                            Phone = "09111111111"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Junie's Address, USA",
                            ContactEntityCategoryId = 4,
                            ContactName = "Junie Pascal",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3242), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Junie@Email.com",
                            FirstName = "Junie",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Jones",
                            Phone = "01011331111"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Mark's Address, Canada",
                            ContactEntityCategoryId = 6,
                            ContactName = "Mark Landis",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3244), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Mark@Email.com",
                            FirstName = "Mark",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "Jones",
                            Phone = "04111117512"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Mygonne's Address, Jamaica",
                            ContactEntityCategoryId = 1,
                            ContactName = "Mygonne McNally",
                            CreatedDate = new DateTimeOffset(new DateTime(2021, 8, 22, 11, 57, 23, 212, DateTimeKind.Unspecified).AddTicks(3245), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Mygonne@Email.com",
                            FirstName = "Mygonne",
                            Image = "https://localhost:5551/Images/UploadFiles/Default.png",
                            IsChecked = false,
                            LastName = "McNally",
                            Phone = "04119111713"
                        });
                });

            modelBuilder.Entity("Domain.ContactEntityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactEntityCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Unspecified"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Owner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Friend"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("Domain.DevUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToEmailAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DevUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ToEmailAddress = "curious-coder@outlook.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "5ecee26e-0f1e-4897-832c-71ed71abefc5",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "a1db822d-d800-4dcd-8602-ace0cb3f8126",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "98f47ce2-06bc-4019-964a-16e396d2bd1d",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "5db46efd-c596-45d9-8cb7-3bfab099142a",
                            Name = "RegularUser",
                            NormalizedName = "REGULARUSER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.ContactEntity", b =>
                {
                    b.HasOne("Domain.ContactEntityCategory", "ContactEntityCategory")
                        .WithMany("ContactEntities")
                        .HasForeignKey("ContactEntityCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactEntityCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Database.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ContactEntityCategory", b =>
                {
                    b.Navigation("ContactEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
